# Generated by Django 3.1.7 on 2021-10-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='clasificacion',
            field=models.CharField(max_length=280, null=True),
        ),
    ]
