# Generated by Django 3.1.7 on 2021-10-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0002_encuesta_clasificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
