# Generated by Django 3.1.7 on 2021-10-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0003_auto_20211006_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='no_pregunta',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='encuesta',
            unique_together={('no_pregunta', 'categoria')},
        ),
    ]
