# Generated by Django 3.1.7 on 2021-10-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0004_auto_20211025_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='sub_clasificacion',
            field=models.CharField(choices=[('clas1', 'Terremotos'), ('clas2', 'Clima'), ('clas3', 'Riesgos de terceros'), ('clas4', 'Distribución'), ('clas5', 'Antiguedad'), ('clas6', 'Orden y Limpieza'), ('clas7', 'Señalización'), ('clas8', 'Prevención del fuego'), ('clas9', 'Reducción del crecimiento y propagación del fuego'), ('clas10', 'Sistema de detección y alarma de incendios'), ('clas11', 'sistemas fijos de extinción'), ('clas12', 'Extintores portátiles y móviles'), ('clas13', 'Brigada contra incendio'), ('clas14', 'Convenios de cooperativa y ayuda mutua'), ('clas15', 'Procedimientos de MANTTO. e inspección'), ('clas16', 'Procedimientos de seguridad'), ('clas17', 'Protección civil / planes de emergencia / y se cuenta con los procedimientos por escrito para'), ('clas18', 'Seguridad ambiental'), ('clas19', 'Capacitacion y entrenamiento'), ('clas20', 'Procedimientos para control de contratista')], default='clas1', max_length=280),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='clasificacion',
            field=models.CharField(choices=[('clas1', 'Localización'), ('clas2', 'Condiciones de la instalación'), ('clas3', 'Riesgos inherentes a la instaclación'), ('clas4', 'Protección contra incendio'), ('clas5', 'Peligros circundantes al centro de trabajo'), ('clas6', 'Procedimientos administrativos')], default='clas1', max_length=280),
        ),
    ]
