# Generated by Django 3.1.7 on 2021-11-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0005_auto_20211025_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='id',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='no_reporte',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='categoria',
            field=models.CharField(choices=[('categoria1', 'Almacen'), ('categoria2', 'Oficina'), ('categoria3', 'Subestacion')], default='categoria3', max_length=50),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='clasificacion',
            field=models.CharField(choices=[('clas1', 'Localización'), ('clas2', 'Condiciones de la instalación'), ('clas3', 'Riesgos inherentes a la instaclación'), ('clas4', 'Protección contra incendio'), ('clas5', 'Peligros circundantes al centro de trabajo'), ('clas6', 'Procedimientos administrativos'), ('clas7', 'Requerimientos normativos en materia de seguridad')], default='clas3', max_length=280),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='sub_clasificacion',
            field=models.CharField(choices=[('clas1', 'Terremotos'), ('clas2', 'Clima / Riesgos naturales'), ('clas3', 'Riesgos de terceros'), ('clas4', 'Distribución'), ('clas5', 'Antiguedad / Condiciones físicas'), ('clas6', 'Orden y Limpieza'), ('clas21', 'Drenaje'), ('clas22', 'Seguridad y vigilancia'), ('clas24', 'Procedimientos de operación'), ('clas23', 'Título Pendiente'), ('clas7', 'Señalización'), ('clas8', 'Prevención del fuego'), ('clas9', 'Reducción del crecimiento y propagación del fuego'), ('clas10', 'Sistema de detección y alarma de incendios'), ('clas11', 'Sistemas fijos de extinción'), ('clas12', 'Extintores portátiles y móviles'), ('clas13', 'Brigada contra incendio'), ('clas14', 'Convenios de cooperativa y ayuda mutua'), ('clas14', 'Peligros circundantes'), ('clas15', 'Procedimientos de mantenimiento e inspección'), ('clas25', 'Caseta de control de la subestación'), ('clas26', 'Tableros y gabinetes de control'), ('clas27', 'Tablero de corriente directa y corriente alterna'), ('clas28', 'Cargadores de baterías'), ('clas29', 'Cuarto de baterías'), ('clas30', 'Cuarto de control supervisorio'), ('clas31', 'Cuarto de comunicaciones'), ('clas32', 'Transformadores, autotransformadores y reactores'), ('clas33', 'Interruptores'), ('clas34', 'Transformadores de instrumentos (TC´s, TP´s y DP´s)'), ('clas35', 'Cuchillas, apartarrayos, buses y banco de capacitores'), ('clas36', 'Trincheras y ductos de cables'), ('clas37', 'Subestación de servicios propios'), ('clas38', 'Predio de la subestación'), ('clas39', 'Sistema de detección y alarma de incendio en caseta de control'), ('clas40', 'Sistema fijo contraincendio para transformadores y autotransformadores'), ('clas41', 'Agentes pasivos'), ('clas42', 'Programa de trabajo de seguridad, salud y prevención de riesgos'), ('clas16', 'Procedimientos de seguridad'), ('clas17', 'Protección civil / planes de emergencia / y se cuenta con los procedimientos por escrito para'), ('clas18', 'Seguridad ambiental'), ('clas19', 'Capacitacion y entrenamiento'), ('clas20', 'Procedimientos para control de contratistas')], default='clas1', max_length=280),
        ),
    ]
