# Generated by Django 3.1.7 on 2021-11-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0007_auto_20211113_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='anexos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_reporte', models.IntegerField(null=True)),
                ('foto_anexo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'anexos',
                'verbose_name_plural': 'anexos',
                'db_table': 'anexos',
            },
        ),
    ]
