# Generated by Django 3.1.7 on 2021-11-29 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminlte3', '0009_anexos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='categoria',
            field=models.CharField(choices=[('categoria1', 'Almacen'), ('categoria2', 'Oficina'), ('categoria3', 'Subestacion')], default='categoria2', max_length=50),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='clasificacion',
            field=models.CharField(choices=[('clas1', 'Localización'), ('clas2', 'Condiciones de la instalación'), ('clas3', 'Riesgos inherentes a la instaclación'), ('clas4', 'Protección contra incendio'), ('clas5', 'Peligros circundantes al centro de trabajo'), ('clas6', 'Procedimientos administrativos'), ('clas7', 'Requerimientos normativos en materia de seguridad')], default='clas6', max_length=280),
        ),
        migrations.CreateModel(
            name='porfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('centro_trabajo', models.CharField(max_length=80)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfil',
                'db_table': 'perfil',
            },
        ),
    ]
