# Generated by Django 3.1.7 on 2021-12-29 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminlte3', '0012_auto_20211205_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuesta',
            options={'ordering': ['no_pregunta'], 'verbose_name': 'encuesta', 'verbose_name_plural': 'encuestas'},
        ),
        migrations.AddField(
            model_name='anexos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='categoria',
            field=models.CharField(choices=[('categoria1', 'Almacén'), ('categoria2', 'Oficina'), ('categoria3', 'Subestación')], default='categoria1', max_length=50),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='clasificacion',
            field=models.CharField(choices=[('clas1', 'Localización'), ('clas2', 'Condiciones de la instalación'), ('clas3', 'Riesgos inherentes a la instalación'), ('clas4', 'Protección contra incendio'), ('clas5', 'Peligros circundantes al centro de trabajo'), ('clas6', 'Procedimientos administrativos'), ('clas7', 'Requerimientos normativos en materia de seguridad')], default='clas6', max_length=280),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='sub_clasificacion',
            field=models.CharField(choices=[('clas1', 'Terremotos'), ('clas2', 'Clima / Riesgos naturales'), ('clas3', 'Riesgos de terceros'), ('clas4', 'Distribución'), ('clas5', 'Antiguedad / Condiciones físicas'), ('clas6', 'Orden y Limpieza'), ('clas7', 'Señalización'), ('clas8', 'Seguridad y vigilancia'), ('clas9', 'Riesgos inherentes'), ('clas10', 'Prevención del fuego'), ('clas11', 'Reducción del crecimiento y propagación del fuego'), ('clas12', 'Sistema de detección y alarma de incendios'), ('clas13', 'Sistemas fijos de extinción'), ('clas14', 'Extintores portátiles y móviles'), ('clas15', 'Brigada contra incendio'), ('clas16', 'Convenios de cooperación y ayuda mutua'), ('clas17', 'Peligros circundantes'), ('clas18', 'Procedimientos de mantenimiento e inspección'), ('clas19', 'Procedimientos de seguridad'), ('clas20', 'Protección civil / planes de emergencia / y se cuenta con los procedimientos por escrito para'), ('clas21', 'Seguridad ambiental'), ('clas22', 'Capacitacion y entrenamiento'), ('clas23', 'Procedimientos para control de contratistas'), ('clas24', 'Drenaje'), ('clas25', 'Procedimientos de operación'), ('clas26', 'Caseta de control de la subestación'), ('clas27', 'Tableros y gabinetes de control'), ('clas28', 'Tablero de corriente directa y corriente alterna'), ('clas29', 'Cargadores de baterías'), ('clas30', 'Cuarto de baterías'), ('clas31', 'Cuarto de control supervisorio'), ('clas32', 'Cuarto de comunicaciones'), ('clas33', 'Transformadores, autotransformadores y reactores'), ('clas34', 'Interruptores'), ('clas35', 'Transformadores de instrumentos (TC´s, TP´s y DP´s)'), ('clas36', 'Cuchillas, apartarrayos, buses y banco de capacitores'), ('clas37', 'Trincheras y ductos de cables'), ('clas38', 'Subestación de servicios propios'), ('clas39', 'Predio de la subestación'), ('clas40', 'Sistema de detección y alarma de incendio en caseta de control'), ('clas41', 'Sistema fijo contraincendio para transformadores y autotransformadores'), ('clas42', 'Agentes pasivos'), ('clas43', 'Programa de trabajo de seguridad, salud y prevención de riesgos')], default='clas1', max_length=280),
        ),
        migrations.AlterField(
            model_name='porfile',
            name='centro_trabajo',
            field=models.CharField(choices=[('SEDE', 'SEDE'), ('Villahermosa', 'Villahermosa'), ('Tuxtla gutierrez', 'Tuxtla gutierrez'), ('Tapachula', 'Tapachula'), ('Itsmo', 'Itsmo'), ('Malpaso', 'Malpaso'), ('Zotze', 'Zotze')], default='sede', max_length=80),
        ),
    ]
